Corrected a dirq diagnostic when failing to initialize a state variable. Corrected a dirqst check on the value of a state variable to work around a bug in expr.

diff --git a/dirq b/dirq
--- a/dirq
+++ b/dirq
@@ -1058,7 +1058,7 @@ fi
 st=$?
 if [ $st != 0 ]
 then
-	echo "${me}: Failed to set dirq state to $state_initialize"
+	echo "${me}: Failed to set dirq state to $state_initialize" 1>&2
 	echo "${me}: Failed to set specified state values in $dir ($st)" 1>&2
 	rm -rf "$dir"
 	exit 2
diff --git a/dirqst b/dirqst
--- a/dirqst
+++ b/dirqst
@@ -210,15 +210,11 @@ else
 				# Entire argument must contain printable characters; no
 				# controls, newlines, etc. are allowed.  First character of
 				# the new state value must be non-blank.
-				expr "x$p" : 'x[A-Za-z][A-Za-z0-9\-_]*=[!-z{}|~][ -z{}|~]*$' > "$nulldev"
-				if [ $? != 0 ]
+				expr "x$p" : 'x[A-Za-z][A-Za-z0-9\-_]*=[ 	][ 	]*$' > "$nulldev"
+				if [ $? -eq 0 ]
 				then
-					expr "x$p" : 'x[A-Za-z][A-Za-z0-9\-_]*=$' > "$nulldev"
-					if [ $? != 0 ]
-					then
-						echo "${me}: Value of $id is invalid." 1>&2
-						bad=1
-					fi
+					echo "${me}: Value of $id is invalid." 1>&2
+					bad=1
 				fi
 			fi
 		done
