Made the following changes:
- Removed the -d option from the dirq and dirqst programs because that
  feature is dubious and it relies on a non-portable feature of the
  Unix "join" command.
- Corrected the parsing of command line switches.
- Issued a diagnostic if the dirq command's type-name parameter is required
  but omitted.
- Corrected sort key specifications.
- Corrected quoting within backtick commands.
- Reordered examples in the dirq.dat file, and added the pipeline example.
- Updated the man pages.

diff --git a/dirq b/dirq
--- a/dirq
+++ b/dirq
@@ -8,6 +8,8 @@
 
 # Identify platform, set platform-specific features.
 
+export LANG=C
+
 platform=`uname`
 if [ $? != 0 -o "x$platform" = "xWindows_NT" ]
 then
@@ -91,10 +93,9 @@ usage() {
 cat << EOF
 ${me}:  Usage:
 ${me}: ${me} [-f file] -t [type-name]
-${me}: ${me} [-f file] -l [-L][-P prefix][-s[-d]|-w] type-name
+${me}: ${me} [-f file] -l [-L][-P prefix][-s|-w] type-name
 ${me}: ${me} [-f file] [-L][-n][-N length][-p][-P prefix][-r] type-name \\
 ${me}:       [state=value]...
-${me}: -d = displays default value of states if unset
 ${me}: -f file = specifies ${me} data file (default $dirqdat)
 ${me}: -l = lists contents of queue
 ${me}: -L = defeats locking (not recommended)
@@ -122,7 +123,6 @@ DUALCASE=1
 
 bad=0
 debug=0
-default=
 length=
 list=0
 listpred=0
@@ -134,12 +134,9 @@ nolock=
 nop=0
 prefix=
 qtype=
-while getopts "df:hlLnN:pP:rstwX" c
+while getopts "f:hlLnN:pP:rstwX" c
 do
 	case "$c" in
-	d)
-		default="-d"
-		;;
 	f)
 		dirqdat="$OPTARG"
 		;;
@@ -181,9 +178,8 @@ do
 		debug=1
 		;;
 	esac
-	shift `expr $OPTIND - 1`
-	OPTIND=1
 done
+shift `expr $OPTIND - 1`
 
 
 # Fetch queue type.
@@ -213,6 +209,12 @@ then
 	then
 		echo "${me}: WARNING: -L has no effect in combination with -t" 1>&2
 	fi
+else
+	if [ "x$qtype" = "x" ]
+	then
+		echo "${me}: type-name is a required parameter." 1>&2
+		bad=1
+	fi
 fi
 
 if [ $liststate != 0 ]
@@ -228,12 +230,6 @@ then
 		echo "${me}: -s is incompatible with -w" 1>&2
 		bad=1
 	fi
-fi
-
-if [ "x$default" != "x" -a $liststate = 0 ]
-then
-	echo "${me}: -d requires -l and -s" 1>&2
-	bad=1
 fi
 
 if [ $listweight != 0 ]
@@ -647,7 +643,7 @@ then
 		for d in $matches
 		do
 			echo "$d"
-			$dirqst $default $nolock -f "$dirqdat" "$d" $statuslist
+			$dirqst $nolock -f "$dirqdat" "$d" $statuslist
 			st=$?
 			echo
 			if [ $st2 != 0 ]
@@ -835,7 +831,7 @@ then
 	$2 == "removable"	{ print 0,$3,cnt++,$1 }
 	$2 == "persistent"	{ print 1,$3,cnt++,$1 }
 	' "$tf1" |
-	sort -n -k1,3 > "$tf2"
+	sort -n -k2,4 > "$tf2"
 
 	if [ $debug != 0 ]
 	then
@@ -884,9 +880,9 @@ fi
 
 if [ "x$seq" = "xstamp" ]
 then
-	stamp=`date '+%Y%m%d`
+	stamp=`date '+%Y%m%d'`
 	d="${prefix}-${stamp}"
-	prefpatt=`echo "$prefix" | sed -e 's/[.]/\\&1/g`
+	prefpatt=`echo "$prefix" | sed -e 's/[.]/\\&1/g'`
 	dpatt="${prefpatt}-${stamp}-"
 	if [ "x$predecessor" = "x" ]
 	then
